export default [
  {
    imageUri: require('../assets/1.jpg'),
    heading: 'Name of the food',
    description: 'descripion',
    key: 'first',
    color: '#9dcdfa',
  },
  {
    imageUri: require('../assets/3.jpg'),
    heading: 'Name of the food',
    description: 'descripion',
    key: 'second',
    color: '#db9efa',
  },
  {
    imageUri: require('../assets/3.jpg'),
    heading: 'Name of the food',
    description: 'descripion',
    key: 'third',
    color: '#999',
  },
  {
    imageUri: require('../assets/4.jpg'),
    heading: 'Name of the food',
    description: 'descripion',
    key: 'fourth',
    color: '#a1e3a1',
  },
  {
    imageUri: require('../assets/3.jpg'),
    heading: 'Name of the food',
    description: 'descripion',
    key: 'fifth',
    color: '#db9efa',
  },
  {
    imageUri: require('../assets/3.jpg'),
    heading: 'Name of the food',
    description: 'descripion',
    key: 'sixth',
    color: '#999',
  },
  {
    imageUri: require('../assets/4.jpg'),
    heading: 'Name of the food',
    description: 'descripion',
    key: 'seventh',
    color: '#a1e3a1',
  },
];
